'use strict';function w(g,a,b,d){g.v.jc(g.Xa,a,b,d,void 0)}function C(g,a,b,d){g.v.pa?w(g,a,b,d):g.v.gf()._OnMessageFromDOM({type:"event",component:g.Xa,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function E(g,a,b){g.v.B(g.Xa,a,b)}function F(g,a){for(const [b,d]of a)E(g,b,d)}function I(g){g.Ob||(g.v.Se(g.ae),g.Ob=!0)}window.Qa=class{constructor(g,a){this.v=g;this.Xa=a;this.Ob=!1;this.ae=()=>this.Ca()}ad(){}Ca(){}};function J(g){-1!==g.Na&&(self.clearTimeout(g.Na),g.Na=-1)}
window.Je=class{constructor(g,a){this.Ic=g;this.ug=a;this.Na=-1;this.Pb=-Infinity;this.be=()=>{this.Na=-1;this.Pb=Date.now();this.bb=!0;this.Ic();this.bb=!1};this.Kd=this.bb=!1}c(){J(this);this.be=this.Ic=null}};"use strict";function K(g,a){const b=a.elementId,d=g.ed(b,a);g.Y.set(b,d);a.isVisible||(d.style.display="none");a=g.tc(d);a.addEventListener("focus",()=>{L(g,"elem-focused",b)});a.addEventListener("blur",()=>{L(g,"elem-blurred",b)});g.Jb&&document.body.appendChild(d)}
function M(g,a){E(g,"get-element",b=>{const d=g.Y.get(b.elementId);return a(d,b)})}function L(g,a,b){var d;d||(d={});d.elementId=b;w(g,a,d)}
window.we=class extends self.Qa{constructor(g,a){super(g,a);this.Y=new Map;this.Jb=!0;F(this,[["create",b=>K(this,b)],["destroy",b=>{{b=b.elementId;const d=this.Y.get(b);this.Jb&&d.parentElement.removeChild(d);this.Y.delete(b)}}],["set-visible",b=>{this.Jb&&(this.Y.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Jb){var d=this.Y.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=b.height+"px";b=b.fontSize;
null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{{const d=this.Y.get(b.elementId);this.pc(d,b)}}],["focus",b=>{{const d=this.tc(this.Y.get(b.elementId));b.focus?d.focus():d.blur()}}],["set-css-style",b=>{this.Y.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Y.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Y.get(b.elementId).removeAttribute(b.name)}]]);M(this,b=>b)}ed(){throw Error("required override");}pc(){throw Error("required override");}tc(g){return g}};
"use strict";
{const g=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);function a(e,c){const h=document.createElement("script");h.async=!1;"module"===c&&(h.type="module");if(e.Eg)h.textContent=e.Hg,document.head.appendChild(h);else return new Promise((k,l)=>{h.onload=k;h.onerror=l;h.src=e;document.head.appendChild(h)})}let b=!1,d=!1;function f(){if(!b){try{new Worker("blob://",{get type(){d=!0}})}catch(e){}b=!0}return d}let m=new Audio;const p={"audio/webm; codecs=opus":!!m.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!m.canPlayType("audio/ogg; codecs=opus"),
"audio/webm; codecs=vorbis":!!m.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!m.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!m.canPlayType("audio/mp4"),"audio/mpeg":!!m.canPlayType("audio/mpeg")};m=null;async function v(e){e=await z(e);return(new TextDecoder("utf-8")).decode(e)}function z(e){return new Promise((c,h)=>{const k=new FileReader;k.onload=l=>c(l.target.result);k.onerror=l=>h(l);k.readAsArrayBuffer(e)})}const A=[];let t=0;window.RealFile=window.File;const u=
[],B=new Map,x=new Map;let G=0;const D=[];self.runOnStartup=function(e){if("function"!==typeof e)throw Error("runOnStartup called without a function");D.push(e)};const H=new Set(["cordova","playable-ad","instant-games"]);window.Ba=class e{constructor(c){this.pa=c.Jg;this.na=null;this.D="";this.Xb=c.Gg;this.da=c.ee;this.qb={};this.Ga=this.pb=null;this.Mb=[];this.eb=this.J=this.La=null;this.Ka=-1;this.zg=()=>this.Gf();this.Ja=[];this.L=c.ce;!this.pa||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&
("module"!==this.da||f())||(this.pa=!1);H.has(this.L)&&this.pa&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),this.pa=!1);this.Rb=this.ia=null;"html5"!==this.L&&"playable-ad"!==this.L||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.B("runtime","cordova-fetch-local-file",
h=>this.qf(h));this.B("runtime","create-job-worker",()=>this.rf());"cordova"===this.L?document.addEventListener("deviceready",()=>this.wd(c)):this.wd(c)}c(){this.qc();this.na&&(this.na=this.na.onmessage=null);this.pb&&(this.pb.terminate(),this.pb=null);this.Ga&&(this.Ga.c(),this.Ga=null);this.J&&(this.J.parentElement.removeChild(this.J),this.J=null)}kd(){return g&&"cordova"===this.L}wb(){return g&&H.has(this.L)||navigator.standalone}async wd(c){if("playable-ad"===this.L){this.ia=self.c3_base64files;
this.Rb={};await this.Xe();for(let k=0,l=c.Oa.length;k<l;++k){var h=c.Oa[k].toLowerCase();this.Rb.hasOwnProperty(h)?c.Oa[k]={Eg:!0,Hg:this.Rb[h]}:this.ia.hasOwnProperty(h)&&(c.Oa[k]=URL.createObjectURL(this.ia[h]))}}c.Ag?this.D=c.Ag:(h=location.origin,this.D=("null"===h?"file:///":h)+location.pathname,h=this.D.lastIndexOf("/"),-1!==h&&(this.D=this.D.substr(0,h+1)));c.Lg&&(this.qb=c.Lg);h=new MessageChannel;this.na=h.port1;this.na.onmessage=k=>this._OnMessageFromRuntime(k.data);window.c3_addPortMessageHandler&&
window.c3_addPortMessageHandler(k=>this.Cf(k));this.eb=new self.Fe(this);await N(this.eb);this.ld();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.pa?await this.jf(c,h.port2):await this.hf(c,h.port2)}uc(c){c=this.qb.hasOwnProperty(c)?this.qb[c]:c.endsWith("/workermain.js")&&this.qb.hasOwnProperty("workermain.js")?this.qb["workermain.js"]:"playable-ad"===this.L&&this.ia.hasOwnProperty(c.toLowerCase())?
this.ia[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async bc(c,h,k){if(c.startsWith("blob:"))return new Worker(c,k);if(this.kd()&&"file:"===location.protocol)return c=await this.sb(this.Xb+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),k);c=new URL(c,h);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");c=await c.blob();return new Worker(URL.createObjectURL(c),k)}return new Worker(c,
k)}ua(){return Math.max(window.innerWidth,1)}ta(){return Math.max(window.innerHeight,1)}ld(){if(this.wb()){const c=document.documentElement.style,h=document.body.style,k=window.innerWidth<window.innerHeight,l=k?window.screen.width:window.screen.height;h.height=c.height=(k?window.screen.height:window.screen.width)+"px";h.width=c.width=l+"px"}}ud(c){var h=this.eb;return{baseUrl:this.D,windowInnerWidth:this.ua(),windowInnerHeight:this.ta(),devicePixelRatio:window.devicePixelRatio,isFullscreen:e.ic(),
projectData:c.Qg,scriptsType:c.ee,previewImageBlobs:window.cr_previewImageBlobs||this.ia,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileUrls:window.cr_previewProjectFiles,swClientId:window.Og||"",exportType:c.ce,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Pg,jobScheduler:{inputPort:h.Oc,outputPort:h.Vc,maxNumWorkers:h.wg},supportedAudioFormats:p,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Xb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.Xb+"opus.wasm.wasm",isiOSCordova:this.kd(),isiOSWebView:this.wb(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async jf(c,h){var k=this.uc(c.Kg);this.pb=await this.bc(k,this.D,{type:this.da,name:"Runtime"});this.J=document.createElement("canvas");this.J.style.display="none";k=this.J.transferControlToOffscreen();document.body.appendChild(this.J);window.c3canvas=this.J;this.pb.postMessage(Object.assign(this.ud(c),{type:"init-runtime",isInWorker:!0,messagePort:h,canvas:k,workerDependencyScripts:c.$c||
[],engineScripts:c.Oa,projectScripts:c.rb,mainProjectScript:c.de,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[h,k,...O(this.eb)]);this.Mb=u.map(l=>new l(this));this.td();self.c3_callFunction=(l,n)=>this.La.kf(l,n);"preview"===this.L&&(self.goToLastErrorScript=()=>this.jc("runtime","go-to-last-error-script"))}async hf(c,h){this.J=document.createElement("canvas");this.J.style.display="none";document.body.appendChild(this.J);window.c3canvas=this.J;this.Mb=u.map(n=>new n(this));this.td();var k=
c.Oa.map(n=>"string"===typeof n?(new URL(n,this.D)).toString():n);Array.isArray(c.$c)&&k.unshift(...c.$c);k=await Promise.all(k.map(n=>this.yc(n,this.da)));await Promise.all(k.map(n=>a(n,this.da)));const l=self.C3_ProjectScriptsStatus;if("module"===this.da){k=c.de;const n=c.rb;for(let [r,q]of n)if(q||(q=r),r===k)try{q=await this.yc(q,this.da),await a(q,this.da),"preview"!==this.L||l[r]||this.Ed(r,"main script did not run to completion")}catch(y){this.Ed(r,y)}else if("scriptsInEvents.js"===r||r.endsWith("/scriptsInEvents.js"))q=
await this.yc(q,this.da),await a(q,this.da)}else if(c.rb&&0<c.rb.length)try{if(await Promise.all(c.rb.map(n=>a(n[1],this.da))),Object.values(l).some(n=>!n)){self.setTimeout(()=>this.Fd(l),100);return}}catch(n){console.error("[Preview] Error loading project scripts: ",n);self.setTimeout(()=>this.Fd(l),100);return}"preview"===this.L&&"object"!==typeof self.Mg.Ng?(this.Va(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):
(c=Object.assign(this.ud(c),{isInWorker:!1,messagePort:h,canvas:this.J,runOnStartupFunctions:D}),this.yd(),this.Ga=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.Ga,c))}Fd(c){this.Va();c=`Failed to load project script '${Object.entries(c).filter(h=>!h[1]).map(h=>h[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+c);alert(c)}Ed(c,h){this.Va();console.error(`[Preview] Failed to load project main script (${c}): `,h);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}yd(){this.Va()}Va(){const c=
window.Bg;c&&(c.parentElement.removeChild(c),window.Bg=null)}async rf(){const c=await P(this.eb);return{outputPort:c,transferables:[c]}}gf(){if(this.pa)throw Error("not available in worker mode");return this.Ga}jc(c,h,k,l,n){this.na.postMessage({type:"event",component:c,handler:h,dispatchOpts:l||null,data:k,responseId:null},n)}md(c,h,k,l,n){const r=G++,q=new Promise((y,S)=>{x.set(r,{resolve:y,reject:S})});this.na.postMessage({type:"event",component:c,handler:h,dispatchOpts:l||null,data:k,responseId:r},
n);return q}["_OnMessageFromRuntime"](c){const h=c.type;if("event"===h)return this.wf(c);if("result"===h)this.Jf(c);else if("runtime-ready"===h)this.Kf();else if("alert-error"===h)this.Va(),alert(c.message);else if("creating-runtime"===h)this.yd();else throw Error(`unknown message '${h}'`);}wf(c){const h=c.component,k=c.handler,l=c.data,n=c.responseId;if(c=B.get(h))if(c=c.get(k)){var r=null;try{r=c(l)}catch(q){console.error(`Exception in '${h}' handler '${k}':`,q);null!==n&&this.Eb(n,!1,""+q);return}if(null===
n)return r;r&&r.then?r.then(q=>this.Eb(n,!0,q)).catch(q=>{console.error(`Rejection from '${h}' handler '${k}':`,q);this.Eb(n,!1,""+q)}):this.Eb(n,!0,r)}else console.warn(`[DOM] No handler '${k}' for component '${h}'`);else console.warn(`[DOM] No event handlers for component '${h}'`)}Eb(c,h,k){let l;k&&k.transferables&&(l=k.transferables);this.na.postMessage({type:"result",responseId:c,isOk:h,result:k},l)}Jf(c){const h=c.responseId,k=c.isOk;c=c.result;const l=x.get(h);k?l.resolve(c):l.reject(c);x.delete(h)}B(c,
h,k){let l=B.get(c);l||(l=new Map,B.set(c,l));if(l.has(h))throw Error(`[DOM] Component '${c}' already has handler '${h}'`);l.set(h,k)}static Pa(c){if(u.includes(c))throw Error("DOM handler already added");u.push(c)}td(){for(const c of this.Mb)if("runtime"===c.Xa){this.La=c;return}throw Error("cannot find runtime DOM handler");}Cf(c){this.jc("debugger","message",c)}Kf(){for(const c of this.Mb)c.ad()}static ic(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}Se(c){this.Ja.push(c);
this.Gc()}Vf(c){c=this.Ja.indexOf(c);if(-1===c)throw Error("invalid callback");this.Ja.splice(c,1);this.Ja.length||this.qc()}Gc(){-1===this.Ka&&this.Ja.length&&(this.Ka=requestAnimationFrame(this.zg))}qc(){-1!==this.Ka&&(cancelAnimationFrame(this.Ka),this.Ka=-1)}Gf(){this.Ka=-1;for(const c of this.Ja)c();this.Gc()}sa(c){this.La.sa(c)}Aa(c){this.La.Aa(c)}Fc(){this.La.Fc()}zb(c){this.La.zb(c)}Ee(){return!!p["audio/webm; codecs=opus"]}async sg(c){c=await this.md("runtime","opus-decode",{arrayBuffer:c},
null,[c]);return new Float32Array(c)}De(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}jd(c){return!this.De(c)}async yc(c,h){if("cordova"!==this.L||g||"module"!==h||!c.startsWith("file:")&&!this.jd(c))return c;c.startsWith(this.D)&&(c=c.substr(this.D.length));c=await this.sb(c);return URL.createObjectURL(new Blob([c],{type:"application/javascript"}))}async qf(c){const h=c.filename;switch(c.as){case "text":return await this.ve(h);case "buffer":return await this.sb(h);
default:throw Error("unsupported type");}}dd(c){const h=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((k,l)=>{window.resolveLocalFileSystemURL(h,n=>{n.file(k,l)},l)})}async ve(c){c=await this.dd(c);return await v(c)}rc(){if(A.length&&!(8<=t)){t++;var c=A.shift();this.Ye(c.filename,c.Ig,c.Dg)}}sb(c){return new Promise((h,k)=>{A.push({filename:c,Ig:l=>{t--;this.rc();h(l)},Dg:l=>{t--;this.rc();k(l)}});this.rc()})}async Ye(c,h,k){try{const l=await this.dd(c),n=await z(l);
h(n)}catch(l){k(l)}}async Xe(){const c=[];for(const [h,k]of Object.entries(this.ia))c.push(this.We(h,k));await Promise.all(c)}async We(c,h){if("object"===typeof h)this.ia[c]=new Blob([h.str],{type:h.type}),this.Rb[c]=h.str;else{let k=await this.ef(h);k||(k=this.$e(h));this.ia[c]=k}}async ef(c){try{return await (await fetch(c)).blob()}catch(h){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
h),null}}$e(c){c=this.Pf(c);return this.Ve(c.data,c.Fg)}Pf(c){var h=c.indexOf(",");if(0>h)throw new URIError("expected comma in data: uri");var k=c.substring(h+1);h=c.substring(5,h).split(";");c=h[0]||"";const l=h[2];k="base64"===h[1]||"base64"===l?atob(k):decodeURIComponent(k);return{Fg:c,data:k}}Ve(c,h){var k=c.length;let l=k>>2,n=new Uint8Array(k),r=new Uint32Array(n.buffer,0,l),q,y;for(y=q=0;q<l;++q)r[q]=c.charCodeAt(y++)|c.charCodeAt(y++)<<8|c.charCodeAt(y++)<<16|c.charCodeAt(y++)<<24;for(k&=
3;k--;)n[y]=c.charCodeAt(y),++y;return new Blob([n],{type:h})}}}"use strict";
{const g=self.Ba;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},f={dispatchUserScriptEvent:!0},m={dispatchRuntimeEvent:!0};function p(e){return new Promise((c,h)=>{const k=document.createElement("link");k.onload=()=>c(k);k.onerror=l=>h(l);k.rel=
"stylesheet";k.href=e;document.head.appendChild(k)})}function v(e){return new Promise((c,h)=>{const k=new Image;k.onload=()=>c(k);k.onerror=l=>h(l);k.src=e})}async function z(e){e=URL.createObjectURL(e);try{return await v(e)}finally{URL.revokeObjectURL(e)}}function A(e){return new Promise((c,h)=>{let k=new FileReader;k.onload=l=>c(l.target.result);k.onerror=l=>h(l);k.readAsText(e)})}async function t(e,c,h){if(!/firefox/i.test(navigator.userAgent))return await z(e);var k=await A(e);k=(new DOMParser).parseFromString(k,
"image/svg+xml");const l=k.documentElement;if(l.hasAttribute("width")&&l.hasAttribute("height")){const n=l.getAttribute("width"),r=l.getAttribute("height");if(!n.includes("%")&&!r.includes("%"))return await z(e)}l.setAttribute("width",c+"px");l.setAttribute("height",h+"px");k=(new XMLSerializer).serializeToString(k);e=new Blob([k],{type:"image/svg+xml"});return await z(e)}function u(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const B=new Set(["canvas",
"body","html"]);function x(e){B.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function G(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await z(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const c=e.getBoundingClientRect();document.body.removeChild(e);return[c.width,c.height]}};self.C3_RasterSvgImageBlob=async function(e,
c,h,k,l){e=await t(e,c,h);const n=document.createElement("canvas");n.width=k;n.height=l;n.getContext("2d").drawImage(e,0,0,c,h);return n};let D=!1;document.addEventListener("pause",()=>D=!0);document.addEventListener("resume",()=>D=!1);function H(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}g.Pa(class extends self.Qa{constructor(e){super(e,"runtime");this.Pd=!0;this.Ma=-1;this.Xc="any";this.Gd=this.Hd=!1;this.Rc=this.mb=this.wa=null;e.B("canvas","update-size",k=>
this.Nf(k));e.B("runtime","invoke-download",k=>this.Af(k));e.B("runtime","raster-svg-image",k=>this.Hf(k));e.B("runtime","get-svg-image-size",k=>this.yf(k));e.B("runtime","set-target-orientation",k=>this.Lf(k));e.B("runtime","register-sw",()=>this.If());e.B("runtime","post-to-debugger",k=>this.Ad(k));e.B("runtime","go-to-script",k=>this.Ad(k));e.B("runtime","before-start-ticking",()=>this.pf());e.B("runtime","debug-highlight",k=>this.sf(k));e.B("runtime","enable-device-orientation",()=>this.Ue());
e.B("runtime","enable-device-motion",()=>this.Te());e.B("runtime","add-stylesheet",k=>this.mf(k));e.B("runtime","alert",k=>this.nf(k));e.B("runtime","hide-cordova-splash",()=>this.zf());const c=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",k=>{const l=k.target;c.has(l.tagName.toLowerCase())||u(l)||k.preventDefault()});const h=e.J;window.addEventListener("selectstart",x);window.addEventListener("gesturehold",x);h.addEventListener("selectstart",x);h.addEventListener("gesturehold",
x);window.addEventListener("touchstart",x,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",x,{passive:!1}),h.addEventListener("pointerdown",x)):h.addEventListener("touchstart",x);this.jb=0;window.addEventListener("mousedown",k=>{1===k.button&&k.preventDefault()});window.addEventListener("mousewheel",G,{passive:!1});window.addEventListener("wheel",G,{passive:!1});window.addEventListener("resize",()=>this.Of());e.wb()&&window.addEventListener("focusout",()=>{{const n=
document.activeElement;if(n){var k=n.tagName.toLowerCase();var l=new Set("email number password search tel text url".split(" "));k="textarea"===k?!0:"input"===k?l.has(n.type.toLowerCase()||"text"):u(n)}else k=!1}k||(document.scrollingElement.scrollTop=0)});this.Ha=new Set;this.Sb=new WeakSet;this.ma=!1}pf(){"cordova"===this.v.L?(document.addEventListener("pause",()=>this.Ec(!0)),document.addEventListener("resume",()=>this.Ec(!1))):document.addEventListener("visibilitychange",()=>this.Ec(document.hidden));
return{isSuspended:!(!document.hidden&&!D)}}ad(){window.addEventListener("focus",()=>this.Fb("window-focus"));window.addEventListener("blur",()=>{this.Fb("window-blur",{parentHasFocus:H()});this.jb=0});window.addEventListener("fullscreenchange",()=>this.Ac());window.addEventListener("webkitfullscreenchange",()=>this.Ac());window.addEventListener("mozfullscreenchange",()=>this.Ac());window.addEventListener("fullscreenerror",c=>this.Bc(c));window.addEventListener("webkitfullscreenerror",c=>this.Bc(c));
window.addEventListener("mozfullscreenerror",c=>this.Bc(c));window.addEventListener("keydown",c=>this.zd("keydown",c));window.addEventListener("keyup",c=>this.zd("keyup",c));window.addEventListener("dblclick",c=>this.Cc("dblclick",c,d));window.addEventListener("wheel",c=>this.Ef(c));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",c=>{this.vc(c);this.Ua("pointerdown",c)}),this.v.pa&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.mb=new self.Je(()=>this.cf(),
5),this.mb.Kd=!0,window.addEventListener("pointerrawupdate",c=>this.Ff(c))):window.addEventListener("pointermove",c=>this.Ua("pointermove",c)),window.addEventListener("pointerup",c=>this.Ua("pointerup",c)),window.addEventListener("pointercancel",c=>this.Ua("pointercancel",c))):(window.addEventListener("mousedown",c=>{this.vc(c);this.Dc("pointerdown",c)}),window.addEventListener("mousemove",c=>this.Dc("pointermove",c)),window.addEventListener("mouseup",c=>this.Dc("pointerup",c)),window.addEventListener("touchstart",
c=>{this.vc(c);this.Db("pointerdown",c)}),window.addEventListener("touchmove",c=>this.Db("pointermove",c)),window.addEventListener("touchend",c=>this.Db("pointerup",c)),window.addEventListener("touchcancel",c=>this.Db("pointercancel",c)));const e=()=>this.Fc();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0)}Fb(e,c){w(this,e,c||null,m)}ua(){return this.v.ua()}ta(){return this.v.ta()}Of(){const e=
this.ua(),c=this.ta();this.Fb("window-resize",{innerWidth:e,innerHeight:c,devicePixelRatio:window.devicePixelRatio});this.v.wb()&&(-1!==this.Ma&&clearTimeout(this.Ma),this.Bd(e,c,0))}Wf(e,c,h){-1!==this.Ma&&clearTimeout(this.Ma);this.Ma=setTimeout(()=>this.Bd(e,c,h),48)}Bd(e,c,h){const k=this.ua(),l=this.ta();this.Ma=-1;k!=e||l!=c?this.Fb("window-resize",{innerWidth:k,innerHeight:l,devicePixelRatio:window.devicePixelRatio}):10>h&&this.Wf(k,l,h+1)}Lf(e){this.Xc=e.targetOrientation}og(){const e=this.Xc;
if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(c=>console.warn("[Construct 3] Failed to lock orientation: ",c));else try{let c=!1;screen.lockOrientation?c=screen.lockOrientation(e):screen.webkitLockOrientation?c=screen.webkitLockOrientation(e):screen.mozLockOrientation?c=screen.mozLockOrientation(e):screen.msLockOrientation&&(c=screen.msLockOrientation(e));c||console.warn("[Construct 3] Failed to lock orientation")}catch(c){console.warn("[Construct 3] Failed to lock orientation: ",
c)}}Ac(){const e=g.ic();e&&"any"!==this.Xc&&this.og();w(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.ua(),innerHeight:this.ta()})}Bc(e){console.warn("[Construct 3] Fullscreen request failed: ",e);w(this,"fullscreenerror",{isFullscreen:g.ic(),innerWidth:this.ua(),innerHeight:this.ta()})}Ec(e){e?this.v.qc():this.v.Gc();w(this,"visibilitychange",{hidden:e})}zd(e,c){"Backspace"===c.key&&x(c);const h=b.get(c.code)||c.code;C(this,e,{code:h,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,
ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},d)}Ef(e){w(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,timeStamp:e.timeStamp},d)}Cc(e,c,h){a(c)||C(this,e,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,timeStamp:c.timeStamp},h)}Dc(e,c){if(!a(c)){var h=this.jb;"pointerdown"===e&&0!==h?e="pointermove":"pointerup"===
e&&0!==c.buttons&&(e="pointermove");C(this,e,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:h,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},d);this.jb=c.buttons;this.Cc(c.type,c,f)}}Ua(e,c){if(this.mb&&"pointermove"!==e){var h=this.mb;h.bb||(J(h),h.Pb=Date.now())}h=0;"mouse"===c.pointerType&&(h=this.jb);C(this,e,{pointerId:c.pointerId,pointerType:c.pointerType,
button:c.button,buttons:c.buttons,lastButtons:h,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},d);"mouse"===c.pointerType&&(h="mousemove","pointerdown"===e?h="mousedown":"pointerup"===e&&(h="mouseup"),this.Cc(h,c,f),this.jb=c.buttons)}Ff(e){this.Rc=e;e=this.mb;if(-1===e.Na){var c=Date.now(),h=c-e.Pb,k=e.ug;
h>=k&&e.Kd?(e.Pb=c,e.bb=!0,e.Ic(),e.bb=!1):e.Na=self.setTimeout(e.be,Math.max(k-h,4))}}cf(){this.Ua("pointermove",this.Rc);this.Rc=null}Db(e,c){for(let h=0,k=c.changedTouches.length;h<k;++h){const l=c.changedTouches[h];C(this,e,{pointerId:l.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,width:2*(l.radiusX||l.webkitRadiusX||0),height:2*(l.radiusY||l.webkitRadiusY||0),pressure:l.force||l.webkitForce||0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:l.rotationAngle||0,timeStamp:c.timeStamp},d)}}vc(e){window!==window.top&&window.focus();this.xd(e.target)&&document.activeElement&&!this.xd(document.activeElement)&&document.activeElement.blur()}xd(e){return!e||e===document||e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}Ue(){this.Hd||(this.Hd=!0,window.addEventListener("deviceorientation",e=>this.uf(e)),window.addEventListener("deviceorientationabsolute",e=>this.vf(e)))}Te(){this.Gd||(this.Gd=!0,window.addEventListener("devicemotion",
e=>this.tf(e)))}uf(e){w(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},d)}vf(e){w(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},d)}tf(e){let c=null;var h=e.acceleration;h&&(c={x:h.x||0,y:h.y||0,z:h.z||0});h=null;var k=e.accelerationIncludingGravity;k&&(h={x:k.x||
0,y:k.y||0,z:k.z||0});k=null;const l=e.rotationRate;l&&(k={alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0});w(this,"devicemotion",{acceleration:c,accelerationIncludingGravity:h,rotationRate:k,interval:e.interval,timeStamp:e.timeStamp},d)}Nf(e){const c=this.v,h=c.J;h.style.width=e.styleWidth+"px";h.style.height=e.styleHeight+"px";h.style.marginLeft=e.marginLeft+"px";h.style.marginTop=e.marginTop+"px";c.ld();this.Pd&&(h.style.display="",this.Pd=!1)}Af(e){const c=e.url;e=e.filename;const h=document.createElement("a"),
k=document.body;h.textContent=e;h.href=c;h.download=e;k.appendChild(h);h.click();k.removeChild(h)}async Hf(e){var c=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);c=c?await createImageBitmap(e,c):await createImageBitmap(e);return{imageBitmap:c,transferables:[c]}}async yf(e){return await self.C3_GetSvgImageSize(e.blob)}async mf(e){await p(e.url)}Fc(){var e=[...this.Ha];this.Ha.clear();if(!this.ma)for(const c of e)(e=c.play())&&
e.catch(()=>{this.Sb.has(c)||this.Ha.add(c)})}sa(e){if("function"!==typeof e.play)throw Error("missing play function");this.Sb.delete(e);let c;try{c=e.play()}catch(h){this.Ha.add(e);return}c&&c.catch(()=>{this.Sb.has(e)||this.Ha.add(e)})}Aa(e){this.Ha.delete(e);this.Sb.add(e)}zb(e){this.ma=!!e}zf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}sf(e){if(e.show){this.wa||(this.wa=document.createElement("div"),this.wa.id="inspectOutline",document.body.appendChild(this.wa));
var c=this.wa;c.style.display="";c.style.left=e.left-1+"px";c.style.top=e.top-1+"px";c.style.width=e.width+2+"px";c.style.height=e.height+2+"px";c.textContent=e.name}else this.wa&&(this.wa.style.display="none")}If(){window.C3_RegisterSW&&window.C3_RegisterSW()}Ad(e){window.c3_postToMessagePort&&(e.from="runtime",window.c3_postToMessagePort(e))}kf(e,c){return this.v.md(this.Xa,"js-invoke-function",{name:e,params:c},void 0,void 0)}nf(e){alert(e.message)}})}"use strict";
async function N(g){if(g.tg)throw Error("already initialised");g.tg=!0;var a=g.Wb.uc("dispatchworker.js");g.Kc=await g.Wb.bc(a,g.D,{name:"DispatchWorker"});a=new MessageChannel;g.Oc=a.port1;g.Kc.postMessage({type:"_init","in-port":a.port2},[a.port2]);g.Vc=await P(g)}function O(g){return[g.Oc,g.Vc]}
async function P(g){const a=g.Qd.length;var b=g.Wb.uc("jobworker.js");b=await g.Wb.bc(b,g.D,{name:"JobWorker"+a});const d=new MessageChannel,f=new MessageChannel;g.Kc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":f.port2},[d.port2,f.port2]);g.Qd.push(b);return f.port1}
self.Fe=class{constructor(g){this.Wb=g;this.D=g.D;this.D="preview"===g.L?this.D+"c3/workers/":this.D+g.Xb;this.wg=Math.min(navigator.hardwareConcurrency||2,16);this.Kc=null;this.Qd=[];this.Vc=this.Oc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Ba({Jg:!0,Kg:"workermain.js",Oa:["scripts/c3runtime.js"],rb:[],de:"",ee:"module",Gg:"scripts/",$c:[],ce:"html5"}));"use strict";
async function Q(g,a){a=a.type;let b=!0;0===a?b=await R():1===a&&(b=await T());w(g,"permission-result",{type:a,result:b})}async function R(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(g){return console.warn("[Touch] Failed to request orientation permission: ",g),!1}}
async function T(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(g){return console.warn("[Touch] Failed to request motion permission: ",g),!1}}self.Ba.Pa(class extends self.Qa{constructor(g){super(g,"touch");E(this,"request-permission",a=>Q(this,a))}});"use strict";self.Ba.Pa(class extends self.Qa{constructor(g){super(g,"mouse");E(this,"cursor",a=>{document.documentElement.style.cursor=a})}});
"use strict";
{function g(a){a.stopPropagation()}self.Ba.Pa(class extends self.we{constructor(a){super(a,"button")}ed(a,b){const d=document.createElement("input");var f=d;b.isCheckbox?(d.type="checkbox",f=document.createElement("label"),f.appendChild(d),f.appendChild(document.createTextNode("")),f.style.fontFamily="sans-serif",f.style.userSelect="none",f.style.webkitUserSelect="none",f.style.display="inline-block",f.style.color="black"):d.type="button";f.style.position="absolute";f.addEventListener("touchstart",g);
f.addEventListener("touchmove",g);f.addEventListener("touchend",g);f.addEventListener("mousedown",g);f.addEventListener("mouseup",g);f.addEventListener("keydown",g);f.addEventListener("keyup",g);d.addEventListener("click",()=>{var m={isChecked:d.checked};m.elementId=a;C(this,"click",m)});b.id&&(d.id=b.id);this.pc(f,b);return f}vd(a){return"input"===a.tagName.toLowerCase()?a:a.firstChild}tc(a){return this.vd(a)}pc(a,b){const d=this.vd(a);d.checked=b.isChecked;d.disabled=!b.isEnabled;a.title=b.title;
a===d?d.value=b.text:a.lastChild.textContent=b.text}})}"use strict";
{const g=180/Math.PI;self.ea=class extends self.Qa{constructor(a){super(a,"audio");this.Lb=this.f=null;this.Nb=this.Nc=!1;this.oa=()=>this.pg();this.ba=[];this.C=[];this.ha=null;this.Rd="";this.Sd=-1;this.lb=new Map;this.Sc=1;this.ma=!1;this.Yc=0;this.Zb=1;this.Lc=0;this.Ud="HRTF";this.Ld="inverse";this.Vd=600;this.Td=1E4;this.Xd=1;this.Nd=this.Wc=!1;this.$d=this.v.Ee();this.ca=new Map;this.Ea=new Set;this.Pc=!1;this.Tc="";this.xa=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.Df(b,d);this.Kb=null;
self.C3Audio_GetOutputStream=()=>this.xf();self.C3Audio_DOMInterface=this;F(this,[["create-audio-context",b=>this.Ze(b)],["play",b=>this.Qf(b)],["stop",b=>this.mg(b)],["stop-all",()=>this.ng()],["set-paused",b=>this.fg(b)],["set-volume",b=>this.kg(b)],["fade-volume",b=>this.df(b)],["set-master-volume",b=>this.dg(b)],["set-muted",b=>this.eg(b)],["set-silent",b=>this.hg(b)],["set-looping",b=>this.cg(b)],["set-playback-rate",b=>this.gg(b)],["seek",b=>this.Xf(b)],["preload",b=>this.Rf(b)],["unload",b=>
this.qg(b)],["unload-all",()=>this.rg()],["set-suspended",b=>this.ig(b)],["add-effect",b=>this.rd(b)],["set-effect-param",b=>this.$f(b)],["remove-effects",b=>this.Tf(b)],["tick",b=>this.Mf(b)],["load-state",b=>this.Bf(b)]])}async Ze(a){a.isiOSCordova&&(this.Wc=!0);this.Yc=a.timeScaleMode;this.Ud=["equalpower","HRTF","soundfield"][a.panningModel];this.Ld=["linear","inverse","exponential"][a.distanceModel];this.Vd=a.refDistance;this.Td=a.maxDistance;this.Xd=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.$d||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.sd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.sd()};this.Lb=this.f.createGain();this.Lb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.cc();try{await Promise.all(a.preloadList.map(d=>this.Bb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.f.sampleRate}}sd(){this.Nb||(this.Nc=!1,window.addEventListener("pointerup",this.oa,!0),window.addEventListener("touchend",this.oa,!0),window.addEventListener("click",this.oa,!0),window.addEventListener("keydown",this.oa,!0),this.Nb=!0)}af(){this.Nb&&(this.Nc=!0,window.removeEventListener("pointerup",this.oa,!0),window.removeEventListener("touchend",
this.oa,!0),window.removeEventListener("click",this.oa,!0),window.removeEventListener("keydown",this.oa,!0),this.Nb=!1)}pg(){if(!this.Nc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.af()}}W(){return this.f}cc(){return this.f.currentTime}qa(){return this.Lb}gd(a){return(a=this.ca.get(a.toLowerCase()))?a[0].P():this.qa()}fe(a,b){a=a.toLowerCase();let d=this.ca.get(a);
d||(d=[],this.ca.set(a,d));b.bg(d.length);b.jg(a);d.push(b);this.Dd(a)}Dd(a){let b=this.qa();const d=this.ca.get(a);if(d&&d.length){b=d[0].P();for(let f=0,m=d.length;f<m;++f){const p=d[f];f+1===m?p.S(this.qa()):p.S(d[f+1].P())}}for(const f of this.ka(a))f.Ke(b);this.xa&&this.Tc===a&&(this.xa.disconnect(),this.xa.connect(b))}ub(){return this.Sc}vb(){return this.ma}ag(){this.Nd=!0}ye(a,b){return b?this.v.sg(a).then(d=>{const f=this.f.createBuffer(1,d.length,48E3);f.getChannelData(0).set(d);return f}):
new Promise((d,f)=>{this.f.decodeAudioData(a,d,f)})}sa(a){this.v.sa(a)}Aa(a){this.v.Aa(a)}nd(a){let b=0;for(let d=0,f=this.C.length;d<f;++d){const m=this.C[d];this.C[b]=m;m.K===a?m.c():++b}this.C.length=b}Le(){let a=0;for(let b=0,d=this.ba.length;b<d;++b){const f=this.ba[b];this.ba[a]=f;f.ra()?f.c():++a}this.ba.length=a}*ka(a){if(a)for(const b of this.C)self.ea.ze(b.$,a)&&(yield b);else this.ha&&!this.ha.T()&&(yield this.ha)}async Bb(a,b,d,f,m){for(const p of this.ba)if(p.Sa()===b)return await U(p),
p;if(m)return null;f&&(this.Wc||this.Nd)&&this.Le();m="audio/webm; codecs=opus"===d&&!this.$d;f&&m&&this.ag();a=!f||this.Wc||m?new self.te(this,a,b,d,f,m):new self.re(this,a,b,d,f);this.ba.push(a);await U(a);return a}async sc(a,b,d,f,m){for(const p of this.C)if(p.Sa()===b&&(p.ac()||m))return p.Ne(f),p;a=await this.Bb(a,b,d,m);f="html5"===a.Hc?new self.se(a.i,a,f):new self.ue(a.i,a,f);this.C.push(f);return f}Re(a){let b=this.lb.get(a);if(!b){let d=null;b={Zc:0,promise:new Promise(f=>d=f),resolve:d};
this.lb.set(a,b)}b.Zc++}Uf(a){const b=this.lb.get(a);if(!b)throw Error("expected pending tag");b.Zc--;0===b.Zc&&(b.resolve(),this.lb.delete(a))}oc(a){a||(a=this.Rd);return(a=this.lb.get(a))?a.promise:Promise.resolve()}Cb(){if(0<this.Ea.size)I(this);else for(const a of this.C)if(a.hd()){I(this);break}}Ca(){for(var a of this.Ea)a.Ca();a=this.cc();for(var b of this.C)b.Ca(a);b=this.C.filter(d=>d.hd()).map(d=>d.Ra());w(this,"state",{tickCount:this.Sd,audioInstances:b,analysers:[...this.Ea].map(d=>d.Be())});
0===b.length&&0===this.Ea.size&&this.Ob&&(this.v.Vf(this.ae),this.Ob=!1)}kc(a,b,d){w(this,"trigger",{type:a,tag:b,aiid:d})}async Qf(a){const b=a.originalUrl,d=a.url,f=a.type,m=a.isMusic,p=a.tag,v=a.isLooping,z=a.vol,A=a.pos,t=a.panning;let u=a.off;0<u&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),u=u-a.performanceTime/1E3+a.contextTime):u=u-performance.now()/1E3+this.f.currentTime);this.Rd=p;this.Re(p);try{this.ha=await this.sc(b,d,f,p,m),t?(this.ha.yb(!0),this.ha.Me(t.x,
t.y,t.angle,t.innerAngle,t.outerAngle,t.outerGain),t.hasOwnProperty("uid")&&this.ha.Oe(t.uid)):this.ha.yb(!1),this.ha.Play(v,z,A,u)}catch(B){console.error("[Construct 3] Audio: error starting playback: ",B);return}finally{this.Uf(p)}I(this)}mg(a){a=a.tag;for(const b of this.ka(a))b.la()}ng(){for(const a of this.C)a.la()}fg(a){const b=a.tag;a=a.paused;for(const d of this.ka(b))a?d.Ta():d.xb();this.Cb()}kg(a){const b=a.tag;a=a.vol;for(const d of this.ka(b))d.Ab(a)}async df(a){const b=a.tag,d=a.vol,
f=a.duration;a=a.stopOnEnd;await this.oc(b);for(const m of this.ka(b))m.Ae(d,f,a);this.Cb()}dg(a){this.Sc=a.vol;for(const b of this.C)b.Hb()}eg(a){const b=a.tag;a=a.isMuted;for(const d of this.ka(b))d.od(a)}hg(a){this.ma=a.isSilent;this.v.zb(this.ma);for(const b of this.C)b.Gb()}cg(a){const b=a.tag;a=a.isLooping;for(const d of this.ka(b))d.mc(a)}async gg(a){const b=a.tag;a=a.rate;await this.oc(b);for(const d of this.ka(b))d.qd(a)}async Xf(a){const b=a.tag;a=a.pos;await this.oc(b);for(const d of this.ka(b))d.lc(a)}async Rf(a){const b=
a.originalUrl,d=a.url,f=a.type;a=a.isMusic;try{await this.sc(b,d,f,"",a)}catch(m){console.error("[Construct 3] Audio: error preloading: ",m)}}async qg(a){if(a=await this.Bb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.ba.indexOf(a),-1!==a&&this.ba.splice(a,1)}rg(){for(const a of this.ba)a.c();this.ba.length=0}ig(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.C)b.nc(a);a&&this.f.suspend&&this.f.suspend()}Mf(a){this.Zb=a.timeScale;this.Lc=a.gameTime;this.Sd=a.tickCount;if(0!==
this.Yc)for(var b of this.C)b.Da();(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const f of this.C)f.ga===a&&f.pd(d.x,d.y,d.angle)}}async rd(a){var b=a.type;const d=a.tag;var f=a.params;if("filter"===b)f=new self.le(this,...f);else if("delay"===b)f=new self.je(this,...f);else if("convolution"===b){b=null;try{b=await this.Bb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct 3] Audio: error loading convolution: ",
m);return}f=new self.ie(this,b.aa,...f);f.Yf(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)f=new self.me(this,...f);else if("phaser"===b)f=new self.oe(this,...f);else if("gain"===b)f=new self.ne(this,...f);else if("tremolo"===b)f=new self.qe(this,...f);else if("ringmod"===b)f=new self.pe(this,...f);else if("distortion"===b)f=new self.ke(this,...f);else if("compressor"===b)f=new self.he(this,...f);else if("analyser"===b)f=new self.ge(this,...f);else throw Error("invalid effect type");this.fe(d,
f);this.Cd()}$f(a){const b=a.index,d=a.param,f=a.value,m=a.ramp,p=a.time;a=this.ca.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,f,m,p),this.Cd())}Tf(a){a=a.tag.toLowerCase();const b=this.ca.get(a);if(b&&b.length){for(const d of b)d.c();this.ca.delete(a);this.Dd(a)}}Qe(a){this.Ea.add(a);this.Cb()}Sf(a){this.Ea.delete(a)}Cd(){this.Pc||(this.Pc=!0,Promise.resolve().then(()=>this.bf()))}bf(){const a={};for(const [b,d]of this.ca)a[b]=d.map(f=>f.Ra());w(this,"fxstate",{fxstate:a});this.Pc=!1}async Bf(a){const b=
a.saveLoadMode;if(3!==b)for(var d of this.C)d.ra()&&1===b||(d.ra()||2!==b)&&d.la();for(const f of this.ca.values())for(const m of f)m.c();this.ca.clear();this.Zb=a.timeScale;this.Lc=a.gameTime;d=a.listenerPos;this.f.listener.setPosition(d[0],d[1],d[2]);this.ma=a.isSilent;this.v.zb(this.ma);this.Sc=a.masterVolume;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(m=>this.rd(m))));await Promise.all(d);await Promise.all(a.playing.map(f=>this.lf(f,b)));this.Cb()}async lf(a,b){if(3!==
b){var d=a.bufferOriginalUrl,f=a.bufferUrl,m=a.bufferType,p=a.isMusic,v=a.tag,z=a.isLooping,A=a.volume,t=a.playbackTime;if(!p||1!==b)if(p||2!==b){b=null;try{b=await this.sc(d,f,m,v,p)}catch(u){console.error("[Construct 3] Audio: error loading audio state: ",u);return}b.Ie(a.pan);b.Play(z,A,t,0);a.isPlaying||b.Ta();b.xc(a)}}}Df(a,b){this.xa&&this.xa.disconnect();this.Tc=b.toLowerCase();this.xa=this.f.createMediaStreamSource(a);this.xa.connect(this.gd(this.Tc))}xf(){this.Kb||(this.Kb=this.f.createMediaStreamDestination(),
this.Lb.connect(this.Kb));return this.Kb.stream}static ze(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Pe(a){return a*g}static xe(a){return Math.pow(10,a/20)}static fd(a){return Math.max(Math.min(self.ea.xe(a),1),0)}static He(a){return Math.log(a)/Math.log(10)*20}static Ge(a){return self.ea.He(Math.max(Math.min(a,1),0))}static Cg(a,b){return 1-Math.exp(-b*a)}};self.Ba.Pa(self.ea)}"use strict";function U(g){g.Qb||(g.Qb=g.wc());return g.Qb}
self.bd=class{constructor(g,a,b,d,f){this.i=g;this.yg=a;this.ya=b;this.R=d;this.vg=f;this.Hc="";this.Qb=null}c(){this.Qb=this.i=null}wc(){}W(){return this.i.W()}ec(){return this.yg}Sa(){return this.ya}dc(){return this.R}ra(){return this.vg}fa(){}};"use strict";
self.re=class extends self.bd{constructor(g,a,b,d,f){super(g,a,b,d,f);this.Hc="html5";this.I=new Audio;this.I.crossOrigin="anonymous";this.I.autoplay=!1;this.I.preload="auto";this.fb=this.gb=null;this.I.addEventListener("canplaythrough",()=>!0);this.kb=this.W().createGain();this.ib=null;this.I.addEventListener("canplay",()=>{this.gb&&(this.gb(),this.fb=this.gb=null);!this.ib&&this.I&&(this.ib=this.W().createMediaElementSource(this.I),this.ib.connect(this.kb))});this.onended=null;this.I.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.I.addEventListener("error",m=>{console.error(`[Construct 3] Audio '${this.ya}' error: `,m);this.fb&&(this.fb(m),this.fb=this.gb=null)})}c(){this.i.nd(this);this.kb.disconnect();this.kb=null;this.ib.disconnect();this.ib=null;this.I&&!this.I.paused&&this.I.pause();this.I=this.onended=null;super.c()}wc(){return new Promise((g,a)=>{this.gb=g;this.fb=a;this.I.src=this.ya})}O(){return this.I}fa(){return this.I.duration}};"use strict";
async function V(g){if(g.va)return g.va;var a=g.i.v;if("cordova"===a.L&&a.jd(g.ya)&&"file:"===location.protocol)g.va=await a.sb(g.ya);else{a=await fetch(g.ya);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);g.va=await a.arrayBuffer()}}async function W(g){if(g.aa)return g.aa;g.aa=await g.i.ye(g.va,g.xg);g.va=null}
self.te=class extends self.bd{constructor(g,a,b,d,f,m){super(g,a,b,d,f);this.Hc="webaudio";this.aa=this.va=null;this.xg=!!m}c(){this.i.nd(this);this.aa=this.va=null;super.c()}async wc(){try{await V(this),await W(this)}catch(g){console.error(`[Construct 3] Failed to load audio '${this.ya}': `,g)}}fa(){return this.aa?this.aa.duration:0}};"use strict";
{let g=0;self.cd=class{constructor(a,b,d){this.i=a;this.K=b;this.$=d;this.Ib=g++;this.M=this.W().createGain();this.M.connect(this.qa());this.A=null;this.cb=!1;this.G=!0;this.V=this.ja=this.F=!1;this.ob=1;this.Fa=!1;this.Z=1;a=this.i.Yc;this.Qc=1===a&&!this.ra()||2===a;this.$a=this.ga=-1;this.Zd=!1}c(){this.K=this.i=null;this.A&&(this.A.disconnect(),this.A=null);this.M.disconnect();this.M=null}W(){return this.i.W()}qa(){return this.i.gd(this.$)}ub(){return this.i.ub()}tb(){return this.Qc?this.i.Lc:
performance.now()/1E3}ec(){return this.K.ec()}Sa(){return this.K.Sa()}dc(){return this.K.dc()}ra(){return this.K.ra()}Ne(a){this.$=a}T(){}ac(){}IsPlaying(){return!this.G&&!this.F&&!this.T()}hd(){return!this.G&&!this.T()}za(){}fa(){return this.K.fa()}Play(){}la(){}Ta(){}xb(){}Ab(a){this.ob=a;this.M.gain.cancelScheduledValues(0);this.$a=-1;this.M.gain.value=this.fc()}Ae(a,b,d){if(!this.Fa){a*=this.ub();var f=this.M.gain;f.cancelScheduledValues(0);var m=this.i.cc();b=m+b;f.setValueAtTime(f.value,m);
f.linearRampToValueAtTime(a,b);this.ob=a;this.$a=b;this.Zd=d}}Hb(){this.Ab(this.ob)}Ca(a){-1!==this.$a&&a>=this.$a&&(this.$a=-1,this.Zd&&this.la(),this.i.kc("fade-ended",this.$,this.Ib))}fc(){const a=this.ob*this.ub();return isFinite(a)?a:0}od(a){a=!!a;this.Fa!==a&&(this.Fa=a,this.Gb())}vb(){return this.i.vb()}Gb(){}mc(){}qd(a){this.Z!==a&&(this.Z=a,this.Da())}Da(){}lc(){}nc(){}yb(a){a=!!a;this.cb!==a&&((this.cb=a)?(this.A||(this.A=this.W().createPanner(),this.A.panningModel=this.i.Ud,this.A.distanceModel=
this.i.Ld,this.A.refDistance=this.i.Vd,this.A.maxDistance=this.i.Td,this.A.rolloffFactor=this.i.Xd),this.M.disconnect(),this.M.connect(this.A),this.A.connect(this.qa())):(this.A.disconnect(),this.M.disconnect(),this.M.connect(this.qa())))}Me(a,b,d,f,m,p){this.cb&&(this.pd(a,b,d),a=self.ea.Pe,this.A.coneInnerAngle=a(f),this.A.coneOuterAngle=a(m),this.A.coneOuterGain=p)}pd(a,b,d){this.cb&&(this.A.setPosition(a,b,0),this.A.setOrientation(Math.cos(d),Math.sin(d),0))}Oe(a){this.ga=a}hc(){}Ke(a){const b=
this.A||this.M;b.disconnect();b.connect(a)}Ra(){return{aiid:this.Ib,tag:this.$,duration:this.fa(),volume:this.ob,isPlaying:this.IsPlaying(),playbackTime:this.za(),playbackRate:this.Z,uid:this.ga,bufferOriginalUrl:this.ec(),bufferUrl:"",bufferType:this.dc(),isMusic:this.ra(),isLooping:this.V,isMuted:this.Fa,resumePosition:this.hc(),pan:this.Ce()}}xc(a){this.qd(a.playbackRate);this.od(a.isMuted)}Ce(){if(!this.A)return null;const a=this.A;return{pos:[a.positionX.value,a.positionY.value,a.positionZ.value],
orient:[a.orientationX.value,a.orientationY.value,a.orientationZ.value],cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ga}}Ie(a){a?(this.yb(!0),a=this.A,a.setPosition(...a.pos),a.setOrientation(...a.orient),a.coneInnerAngle=a.cia,a.coneOuterAngle=a.coa,a.coneOuterGain=a.cog,this.ga=a.uid):this.yb(!1)}}}"use strict";
self.se=class extends self.cd{constructor(g,a,b){super(g,a,b);this.K.kb.connect(this.M);this.K.onended=()=>this.zc()}c(){this.la();this.K.kb.disconnect();super.c()}O(){return this.K.O()}zc(){this.G=!0;this.ga=-1;this.i.kc("ended",this.$,this.Ib)}T(){return this.O().ended}ac(){return this.G?!0:this.T()}za(g){let a=this.O().currentTime;g&&(a*=this.Z);this.V||(a=Math.min(a,this.fa()));return a}Play(g,a,b){const d=this.O();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==g&&(d.loop=g);this.Ab(a);d.muted&&
(d.muted=!1);if(d.currentTime!==b)try{d.currentTime=b}catch(f){console.warn(`[Construct 3] Exception seeking audio '${this.K.Sa()}' to position '${b}': `,f)}this.i.sa(d);this.F=this.G=!1;this.V=g;this.Z=1}la(){const g=this.O();g.paused||g.pause();this.i.Aa(g);this.G=!0;this.F=!1;this.ga=-1}Ta(){if(!(this.F||this.G||this.T())){var g=this.O();g.paused||g.pause();this.i.Aa(g);this.F=!0}}xb(){!this.F||this.G||this.T()||(this.i.sa(this.O()),this.F=!1)}Gb(){this.O().muted=this.Fa||this.vb()}mc(g){g=!!g;
this.V!==g&&(this.V=g,this.O().loop=g)}Da(){let g=this.Z;this.Qc&&(g*=this.i.Zb);try{this.O().playbackRate=g}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${g}':`,a)}}lc(g){if(!this.G&&!this.T())try{this.O().currentTime=g}catch(a){console.warn(`[Construct 3] Error seeking audio to '${g}': `,a)}}hc(){return this.za()}nc(g){g?this.IsPlaying()?(this.O().pause(),this.ja=!0):this.ja=!1:this.ja&&(this.i.sa(this.O()),this.ja=!1)}};"use strict";
function X(g){g.j&&g.j.disconnect();g.j=null;g.Wa=null}
self.ue=class extends self.cd{constructor(g,a,b){super(g,a,b);this.j=null;this.Tb=d=>this.zc(d);this.Mc=!0;this.Wa=null;this.N=this.Yb=0;this.Uc=1}c(){this.la();X(this);this.Tb=null;super.c()}zc(g){this.F||this.ja||g.target!==this.Wa||(this.G=this.Mc=!0,this.ga=-1,X(this),this.i.kc("ended",this.$,this.Ib))}T(){return!this.G&&this.j&&this.j.loop||this.F?!1:this.Mc}ac(){return!this.j||this.G?!0:this.T()}za(g){let a;a=this.F?this.N:this.tb()-this.Yb;g&&(a*=this.Z);this.V||(a=Math.min(a,this.fa()));return a}Play(g,
a,b,d){this.Uc=1;this.Ab(a);X(this);this.j=this.W().createBufferSource();this.j.buffer=this.K.aa;this.j.connect(this.M);this.Wa=this.j;this.j.onended=this.Tb;this.j.loop=g;this.j.start(d,b);this.F=this.G=this.Mc=!1;this.V=g;this.Z=1;this.Yb=this.tb()-b}la(){if(this.j)try{this.j.stop(0)}catch(g){}this.G=!0;this.F=!1;this.ga=-1}Ta(){this.F||this.G||this.T()||(this.N=this.za(!0),this.V&&(this.N%=this.fa()),this.F=!0,this.j.stop(0))}xb(){!this.F||this.G||this.T()||(X(this),this.j=this.W().createBufferSource(),
this.j.buffer=this.K.aa,this.j.connect(this.M),this.Wa=this.j,this.j.onended=this.Tb,this.j.loop=this.V,this.Hb(),this.Da(),this.Yb=this.tb()-this.N/(this.Z||.001),this.j.start(0,this.N),this.F=!1)}fc(){return super.fc()*this.Uc}Gb(){this.Uc=this.Fa||this.vb()?0:1;this.Hb()}mc(g){g=!!g;this.V!==g&&(this.V=g,this.j&&(this.j.loop=g))}Da(){let g=this.Z;this.Qc&&(g*=this.i.Zb);this.j&&(this.j.playbackRate.value=g)}lc(g){this.G||this.T()||(this.F?this.N=g:(this.Ta(),this.N=g,this.xb()))}hc(){return this.N}nc(g){g?
this.IsPlaying()?(this.ja=!0,this.N=this.za(!0),this.V&&(this.N%=this.fa()),this.j.stop(0)):this.ja=!1:this.ja&&(X(this),this.j=this.W().createBufferSource(),this.j.buffer=this.K.aa,this.j.connect(this.M),this.Wa=this.j,this.j.onended=this.Tb,this.j.loop=this.V,this.Hb(),this.Da(),this.Yb=this.tb()-this.N/(this.Z||.001),this.j.start(0,this.N),this.ja=!1)}xc(g){super.xc(g);this.N=g.resumePosition}};"use strict";
{class g{constructor(a){this.i=a;this.f=a.W();this.Od=-1;this.R=this.$="";this.g=null}c(){this.f=null}bg(a){this.Od=a}jg(a){this.$=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,d,f){a.cancelScheduledValues(0);if(0===f)a.value=b;else{var m=this.f.currentTime;f+=m;switch(d){case 0:a.setValueAtTime(b,f);break;case 1:a.setValueAtTime(a.value,m);a.linearRampToValueAtTime(b,f);break;case 2:a.setValueAtTime(a.value,m),a.exponentialRampToValueAtTime(b,f)}}}Ra(){return{type:this.R,tag:this.$,params:this.g}}}
self.le=class extends g{constructor(a,b,d,f,m,p,v){super(a);this.R="filter";this.g=[b,d,f,m,p,v];this.l=this.o();this.b=this.o();this.b.gain.value=v;this.a=this.o();this.a.gain.value=1-v;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=d;this.u.detune.value=f;this.u.Q.value=m;this.u.gain.vlaue=p;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,f);this.m(this.a.gain,1-b,d,f);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,d,f);break;case 2:this.g[2]=b;this.m(this.u.detune,b,d,f);break;case 3:this.g[3]=b;this.m(this.u.Q,b,d,f);break;case 4:this.g[4]=b,this.m(this.u.gain,b,d,f)}}};self.je=class extends g{constructor(a,b,d,f){super(a);this.R="delay";this.g=[b,d,f];this.l=
this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=1-f;this.hb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.Za=this.o();this.Za.gain.value=d;this.l.connect(this.hb);this.l.connect(this.a);this.hb.connect(this.b);this.hb.connect(this.U);this.U.connect(this.Za);this.Za.connect(this.hb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.hb.disconnect();this.U.disconnect();this.Za.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){const m=self.ea.fd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,f);this.m(this.a.gain,1-b,d,f);break;case 4:this.g[1]=m(b);this.m(this.Za.gain,m(b),d,f);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,d,f)}}};self.ie=class extends g{constructor(a,b,d,f){super(a);this.R="convolution";this.g=[d,f];this.Jd=this.Id="";this.l=this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=
1-f;this.Ya=this.f.createConvolver();this.Ya.normalize=d;this.Ya.buffer=b;this.l.connect(this.Ya);this.l.connect(this.a);this.Ya.connect(this.b)}c(){this.l.disconnect();this.Ya.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,f),this.m(this.a.gain,1-b,d,f)}}Yf(a,b){this.Id=a;this.Jd=b}Ra(){const a=
super.Ra();a.bufferOriginalUrl=this.Id;a.bufferUrl="";a.bufferType=this.Jd;return a}};self.me=class extends g{constructor(a,b,d,f,m,p){super(a);this.R="flanger";this.g=[b,d,f,m,p];this.l=this.o();this.a=this.o();this.a.gain.value=1-p/2;this.b=this.o();this.b.gain.value=p/2;this.ab=this.o();this.ab.gain.value=m;this.U=this.f.createDelay(b+d);this.U.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=f;this.H=this.o();this.H.gain.value=d;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.ab);this.ab.connect(this.U);this.s.connect(this.H);this.H.connect(this.U.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.H.disconnect();this.a.disconnect();this.b.disconnect();this.ab.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,f);this.m(this.a.gain,1-b/2,d,f);break;case 6:this.g[1]=b/1E3;this.m(this.H.gain,b/1E3,d,f);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,d,f);break;case 8:this.g[3]=b/100,this.m(this.ab.gain,b/100,d,f)}}};self.oe=class extends g{constructor(a,b,d,f,m,p,v){super(a);this.R="phaser";this.g=[b,d,f,m,p,v];this.l=this.o();this.a=this.o();this.a.gain.value=1-v/2;this.b=this.o();this.b.gain.value=v/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
d;this.u.Q.value=f;this.s=this.f.createOscillator();this.s.frequency.value=p;this.H=this.o();this.H.gain.value=m;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.H);this.H.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.H.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,f);this.m(this.a.gain,1-b/2,d,f);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,d,f);break;case 2:this.g[1]=b;this.m(this.u.detune,b,d,f);break;case 3:this.g[2]=b;this.m(this.u.Q,b,d,f);break;case 6:this.g[3]=b;this.m(this.H.gain,b,d,f);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,d,f)}}};self.ne=class extends g{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,f){const m=self.ea.fd;switch(a){case 4:this.g[0]=m(b),this.m(this.h.gain,m(b),d,f)}}};self.qe=class extends g{constructor(a,b,d){super(a);this.R="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.H=this.o();this.H.gain.value=d/2;this.s.connect(this.H);this.H.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.H.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,d,f);this.m(this.H.gain,b/2,d,f);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,f)}}};self.pe=class extends g{constructor(a,b,d){super(a);this.R="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.nb=this.o();this.nb.gain.value=
0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.nb.gain);this.s.start(0);this.l.connect(this.nb);this.l.connect(this.a);this.nb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.nb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,d,f);
this.m(this.a.gain,1-b,d,f);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,f)}}};self.ke=class extends g{constructor(a,b,d,f,m,p){super(a);this.R="distortion";this.g=[b,d,f,m,p];this.l=this.o();this.Vb=this.o();this.Ub=this.o();this.Zf(f,m);this.b=this.o();this.b.gain.value=p;this.a=this.o();this.a.gain.value=1-p;this.$b=this.f.createWaveShaper();this.Jc=new Float32Array(65536);this.ff(b,d);this.$b.curve=this.Jc;this.l.connect(this.Vb);this.l.connect(this.a);this.Vb.connect(this.$b);this.$b.connect(this.Ub);
this.Ub.connect(this.b)}c(){this.l.disconnect();this.Vb.disconnect();this.$b.disconnect();this.Ub.disconnect();this.b.disconnect();this.a.disconnect();super.c()}Zf(a,b){.01>a&&(a=.01);this.Vb.gain.value=a;this.Ub.gain.value=Math.pow(1/a,.6)*b}ff(a,b){for(let d=0;32768>d;++d){let f=d/32768;f=this.lg(f,a,b);this.Jc[32768+d]=f;this.Jc[32768-d-1]=-f}}lg(a,b,d){d=1.05*d*b-b;const f=0>a?-a:a;return(f<b?f:b+d*self.ea.Cg(f-b,1/d))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,f),this.m(this.a.gain,1-b,d,f)}}};self.he=class extends g{constructor(a,b,d,f,m,p){super(a);this.R="compressor";this.g=[b,d,f,m,p];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=f;this.h.attack.value=m;this.h.release.value=p}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.ge=class extends g{constructor(a,b,d){super(a);this.R="analyser";this.g=[b,d];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.Md=new Float32Array(this.h.frequencyBinCount);this.Yd=new Uint8Array(b);this.Wd=this.Ia=0;this.i.Qe(this)}c(){this.i.Sf(this);this.h.disconnect();super.c()}Ca(){this.h.getFloatFrequencyData(this.Md);this.h.getByteTimeDomainData(this.Yd);const a=this.h.fftSize;let b=this.Ia=0;for(var d=0;d<a;++d){let f=(this.Yd[d]-128)/128;0>f&&(f=-f);
this.Ia<f&&(this.Ia=f);b+=f*f}d=self.ea.Ge;this.Ia=d(this.Ia);this.Wd=d(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}Be(){return{tag:this.$,index:this.Od,peak:this.Ia,rms:this.Wd,binCount:this.h.frequencyBinCount,freqBins:this.Md}}}};
